name: Publish Icons

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'packages/core/icons/svg/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build Icons
        run: pnpm --filter @phill-component/icons run build
        
      - name: Publish to NPM
        run: pnpm --filter @phill-component/icons run release-core-icons
        env:
          PHILLUI_PUBLISH: 1
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
